### ISSUE TITLE
Excel_Toolkit: Crashing on exit

### ISSUE THREAD

**Issue by rwemay** [BHoM/Excel_UI#171]
#### Description:

Excel is hogging processes on exit and crashing, needing to force-close through task manager before re-opening Excel. 

#### How to replicate:

Run the sample script below. Be sure to check 64 bit version as this is what all users will be switched to. 

#### Expected behaviour:

Excel should close without crashing, and release all processes. 

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/Issues?csf=1&e=O2WO6m

**Comment by awakeman** [comment]
Unable to reproduce with the above script, will liaise with you in person to try to get to the bottom of it.

**Comment by awakeman** [comment]
@jdarcyBHE have you experienced this issue?

**Comment by jdarcyBHE** [comment]
Well I appear to have a larger issue, currently I can't access the BHoM in excel it freezes and then crashes.

**Comment by awakeman** [comment]
that is probably https://github.com/BHoM/BHoM_Engine/issues/1337, fixed by https://github.com/BHoM/BHoM_Engine/pull/1338, try updating.

**Comment by jdarcyBHE** [comment]
Updated to latest alpha build and excel BHoM is working.

Ran the test script and I don't experience any issues with excel crashing out.

**Comment by FraserGreenroyd** [comment]
As discussed in today's PR closure call, I have had a look at this issue but cannot reproduce the problem. I have used the script provided by @rwemay and tried both without installed Robot and then installing Robot to run the workbook provided, but I could not get Excel to hang or crash on closing.

I imagine this is related to the user machine trying it, so would not feel that this is a critical issue (especially as a workaround exists, the definition of our 'critical' issues is that there is no workaround but task manager does provide one in this instance).

Happy to retest/take another evaluation if further information comes to light.

**Comment by rwemay** [comment]
Happy to close this for now - it's still happening for me, but my machine has quite a long history! I removed dragon and other plugin references from the registry which (incidentally) sped the load time up a bit, but didn't resolve the issue. Given no one else can so far reproduce, I'm going to assume it's just my machine/historic issue for now. Will re-raise as and when I can find a cause related to BHoM.

**Comment by rwemay** [comment]
Crash on exit has worsened in the recent PR and I believe others (@IsakNaslundBh ) are having the issue, so this persists. Did some research this morning and wondering if it's linked to the Timer? @awakeman  thoughts? https://www.add-in-express.com/forum/read.php?FID=5&TID=167

**Comment by rwemay** [comment]
@awakeman , saw there was already an open issue for this so no need to create new.
